### ISSUE TITLE
Не меняются настройки Proxycap

### ISSUE THREAD

**Issue by handikraft** [vladislav-puzyrev/autosurf-bootstrap#1]
Не меняются настройки Proxycap. Возможно где то ошибка в скрипте. Помогите пожалуйста .Скрипт мне очень интересен в плане пользования

**Comment by vladpuz** [comment]
@handikraft Какую версию `ProxyCap` вы используете? Работало на `ProxyCap 5.35`. Скрипт не выдает ошибок?

**Comment by handikraft** [comment]
proxycap версии 5.35 по вашей ссылке скачивал

**Comment by handikraft** [comment]
первый раз при создании, ошибок скрипт не выдает . если потом запустить скрипт удаления настроек , потом вновь запустить создание настроек ,выбивает ошибку файла настроек ,ini  sandboxie. лечится переустановкой sandboxie. версия последняя скачанная с сайта.  В sandboxie  песочницы создаются, копии webisida создаются, а в proxycap настройки не появляются

**Comment by handikraft** [comment]
забыл сказать. в логе при установке пишет что ошибок никаких нет скрипт завершен удачно

**Comment by vladpuz** [comment]
> первый раз при создании, ошибок скрипт не выдает . если потом запустить скрипт удаления настроек , потом вновь запустить создание настроек ,выбивает ошибку файла настроек ,ini sandboxie. лечится переустановкой sandboxie. версия последняя скачанная с сайта. В sandboxie песочницы создаются, копии webisida создаются, а в proxycap настройки не появляются

Отправьте пожалуйста скриншот ошибки файла `Sandboxie.ini`, у меня не воспроизводится. Думаю вместо переустановки `Sandboxie` вам будет достаточно просто удалить файл `C:/Windows/Sandboxie.ini` и перезапустить `Sandboxie`. Возможно проблема из-за того, что у скрипта нет доступа к `C:/Windows/Sandboxie.ini`? Я использую его без антивирусов в системе, с отключенным `SmartScreen` под учетной записью администратора.

Что касается проблемы с конфигурацией `ProxyCap`, проверьте активирована ли у вас программа в разделе `About ProxyCap`. Должно быть такое окно:

![Screenshot_4](https://user-images.githubusercontent.com/52296792/146928201-817b9133-a9cd-4cff-95a8-931a6898ce49.png)

Я проделал следующие шаги по запуску:

1. Скачайте portable версии нужных автосерферов.
2. Поместите файлы автосерферов по пути `autosurf-bootstrap/surfers/[surfer]/copy`
3. Запустите и настройте автосерферы. Эти настройки будут скопированы на каждую созданную копию программ. Закройте все автосерферы перед следующим шагом.

Далее я выполнил команды:

```shell
yarn install
yarn run bootstrap
```

И проверив `ProxyCap` получил настроенные тестовые прокси:

![Screenshot_6](https://user-images.githubusercontent.com/52296792/146929008-a2a80b82-ca2c-4bbf-8e1a-8ad02c7428e1.png)

**Comment by handikraft** [comment]
хотел еще уточнить у вас в с тарой версии readme указано что прокси указываются в файле с расширением tc  в новой версии readme указано что в файле proxy  он txt. и без переменной,  я не силен в программировании  может в этом у меня загвоздка

**Comment by vladpuz** [comment]
> хотел еще уточнить у вас в с тарой версии readme указано что прокси указываются в файле с расширением tc в новой версии readme указано что в файле proxy он txt. и без переменной, я не силен в программировании может в этом у меня загвоздка

Да, это сделано для того, чтобы можно было указывать разные прокси для `webisida` и `simple`. Попробуйте установить самую последнею версию, сегодня я обновил зависимости проекта на самые свежие. Файлы прокси это обычные текстовики (txt).

**Comment by handikraft** [comment]
обязательно попробую обновлю. благодарю

**Comment by handikraft** [comment]
Попробовал обновленный скрипт установил , все то же -в Proxycap  не  меняются настройки, остальное все работает. В процессе установки выскакивало сообщение запрета запуска скриптов , лечится командой Set-ExecutionPolicy Bypass

![screenshot](https://user-images.githubusercontent.com/96453975/147008338-cb5e8cd2-32ca-4684-b98d-37dd481ff7e1.png)

Антивирус в Windows 10 отключен. Посмотрите скрины может я делаю что не так


![screenshot4](https://user-images.githubusercontent.com/96453975/147009332-9c9b7654-eb37-46e2-bbf4-8a092169657d.png)

![screenshot5](https://user-images.githubusercontent.com/96453975/147009333-d18b1f51-5f96-4133-acc6-391d1c4ac55f.png)

![screenshot6](https://user-images.githubusercontent.com/96453975/147009335-2fac7f1a-2b67-438e-ad54-93af372ed4fe.png)

![screenshot10](https://user-images.githubusercontent.com/96453975/147009336-f2c1190d-cade-4293-92cc-f3090395938d.png)

![screenshot11](https://user-images.githubusercontent.com/96453975/147009338-f1cf0c7b-5303-4352-ae7d-0b777b3bd5c1.png)

![screenshot14](https://user-images.githubusercontent.com/96453975/147009342-2aa081c4-356d-4367-ade9-c91350fe9fa3.png)

**Comment by vladpuz** [comment]
@handikraft Я добавил подробное логирование этапа настройки `ProxyCap` в ветке `issue-1` https://github.com/vladislav-puzyrev/autosurf-bootstrap/tree/issue-1. Установите пожалуйста скрипт оттуда и отправьте скриншот его работы.

По задумке скрипт должен создавать файл конфигурации `machine.prs` по маршруту `C:\ProgramData\ProxyCap\machine.prs`. Ваш `ProxyCap` установлен в стандартной директории? Если нет, попробуйте переустановить в стандартную на всякий случай.

**Comment by handikraft** [comment]
Установка Proxycap  у меня по умолчанию была, директорию не менял. Попробую скрипт с логами . Тогда пришлю скрины лога

**Comment by handikraft** [comment]
![screenshot33](https://user-images.githubusercontent.com/96453975/147082411-b33c6437-9584-4d0a-b50e-5bdba35f7779.png)

Пишет ошибку. Пробовал обновить файл XML2PRS с сайта Proxycap , ничего не поменялось, такая же ошибка

**Comment by handikraft** [comment]
Я попробовал вручную восстановить файл настроек из директории C:\ProgramData\ProxyCap\ , настройки есть измененные. Получается это Proxycap  не подтягивал новые настройки, а после загрузки в него machine.prs заработал. Вероятнее всего необходимо было после запуска скрипта перезагрузить Windows, хотя до этого я перезагружал много раз, эффекта не было. Причем теперь при новом запуске скрипта все работает, настройки меняются. Пробовал много раз, все работает.
![screenshot34](https://user-images.githubusercontent.com/96453975/147094197-37a56850-823a-459d-85bc-0379556feebf.png)
![screenshot35](https://user-images.githubusercontent.com/96453975/147094204-4d85c9da-a9dc-4bff-bdc0-15bc17d30fa9.png)
![screenshot37](https://user-images.githubusercontent.com/96453975/147097287-2c75bb80-a624-4a87-b7e4-5c720ea09f25.png)

Для себя я определился что после запуска скрипта надо загрузить в Proxycap файл настроек C:\ProgramData\ProxyCap\machine.prs - единоразово. После чего все работает в автоматическом режиме.

Еще попробую на чисто все вновь установить , подскажу результат

**Comment by handikraft** [comment]
Добрый день. Переустановил Windows. Установил все программы и запустил скрипт- все работает, по вашей версии2 которая без лога. Благодарю за уделенное мне время. Я для себя накидал последовательность действий на основе вашего описания. С вашего разрешения я его тут выложу
[Readme .txt](https://github.com/vladislav-puzyrev/autosurf-bootstrap/files/7769853/Readme.txt)
